name: open-on-backpack

on: push

defaults:
  run:
    working-directory: ./scrap-tf/open-on-backpack

jobs:
  npm-build:
    name: Test npm build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependency
        run: npm install
        shell: bash

      - name: Run build
        run: npm run build
        shell: bash
